apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jobs
    spec:
      containers:
        - image: gcr.io/bedrock-staging/bedrock-jobs
          imagePullPolicy: Always
          name: main
          env:
            - name: NODE_ENV
              value: "staging"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/bedrock_staging"
            - name: APP_DOMAIN
              value: "bedrock.foundation"
            - name: POSTMARK_FROM
              value: "no-reply@bedrock.foundation"
            - name: POSTMARK_APIKEY
              value: "abc"
          volumeMounts:
            - name: cache
              mountPath: /workdir/data
      volumes:
        - name: cache
          emptyDir: {}
