apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jobs
    spec:
      containers:
        - image: gcr.io/bulkhead-staging/bulkhead-jobs
          imagePullPolicy: Always
          name: jobs
          env:
            - name: NODE_ENV
              value: "prod"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/bulkhead_production"
            - name: APP_DOMAIN
              value: "bulkhead.io"
            - name: POSTMARK_FROM
              value: "no-reply@bulkhead.io"
            - name: POSTMARK_APIKEY
              value: "abc"
          volumeMounts:
            - name: jobs-cache
              mountPath: /workdir/data
      volumes:
        - name: jobs-cache
          emptyDir: {}
