apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-docs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-docs
  template:
    metadata:
      labels:
        app: api-docs
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/bedrock-core-services-api-docs
          imagePullPolicy: Always
          name: main
          env:
            - name: ENABLE_HTTP_BASIC_AUTH
              value: "yes"
            - name: OPENAPI_URL
              value: "https://api.bedrock.foundation/openapi.json"
          envFrom:
            - configMapRef:
                name: global-config
          ports:
            - name: http-server
              containerPort: 2400
          volumeMounts:
            - name: cache
              mountPath: /service/data
      volumes:
        - name: cache
          emptyDir: {}
